CREATE DATABASE BTLC
GO 

CREATE TABLE tTheLoai (
	MaTheLoai NVARCHAR(20) NOT NULL
	CONSTRAINT PK_tTheLoai_MaTheLoai PRIMARY KEY,
	TenTheLoai NVARCHAR(50)
);

CREATE TABLE tNhaXuatBan (
	MaNXB NVARCHAR(20) NOT NULL
	CONSTRAINT PK_tNhaXuatBan_MaNXB PRIMARY KEY,
	TenNXB NVARCHAR(50),
	Email NVARCHAR(30),
	DiaChi NVARCHAR(50)
);

CREATE TABLE tGioiTinh (
	MaGioiTinh BIT NOT NULL
	CONSTRAINT PK_tGioiTinh_MaGioiTinh PRIMARY KEY,
	GioiTinh NVARCHAR(5)
);

CREATE TABLE tSach
(
	MaSach NVARCHAR(20) NOT NULL PRIMARY KEY(MaSach),
	Tensach NVARCHAR(50) NOT NULL,
	TenTacGia NVARCHAR(50) NOT NULL,
	NamXuatBan INT NOT NULL,
	MaNXB NVARCHAR(20),
	LanTaiBan INT,
	SoLuong INT NOT NULL,
	SoTrang INT,
	MaTheLoai NVARCHAR(20),
	CONSTRAINT FK_tSach_MaNXB
				FOREIGN KEY(MaNXB)
				REFERENCES tNhaXuatBan(MaNXB),
	CONSTRAINT FK_tSach_MaTheLoai
				FOREIGN KEY(MaTheLoai) 
				REFERENCES tTheLoai(MaTheLoai)
);

CREATE TABLE tKhoa
(
	MaKhoa VARCHAR(20) NOT NULL PRIMARY KEY(MaKhoa),
	TenKhoa NVARCHAR(50)
)

CREATE TABLE tLop
(
	MaLop VARCHAR(20) NOT NULL PRIMARY KEY(MaLop),
	TenLop NVARCHAR(50)
)

CREATE TABLE tSinhVien
(
	MaSinhVien VARCHAR(20) NOT NULL PRIMARY KEY(MaSinhVien),
	MaKhoa NVARCHAR(20) NOT NULL,
	MaLop NVARCHAR(20) NOT NULL,
	--Thoi gian hoc la hien tai dang nam may
	ThoiGianHoc INT, 
	--So nam hoc la so nam hoc de tot nghiep
	SoNamHoc INT
);
CREATE TABLE tThuThu
(
	MaThuThu NVARCHAR(20) NOT NULL
	CONSTRAINT PK_tThuThu_MaThuThu PRIMARY KEY,
	TenThuThu NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	MaGioiTinh bit,
	SoDienThoai INT NOT NULL,
	DiaChi NVARCHAR(100),
	CONSTRAINT FK_tGioiTinh_MaGioiTinh
				FOREIGN KEY(MaGioiTinh)
				REFERENCES tGioiTinh(MaGioiTinh)
);


CREATE TABLE tTheMuon
(
	MaThe NVARCHAR(10) NOT NULL,
	HoTen NVARCHAR(20) NOT NULL,
	GioiTinh NVARCHAR(5) NOT NULL,
	NgaySinh DATE,
	MaSinhVien INT NOT NULL,
	NgayLamThe DATE NOT NULL,
	NgayHetHan DATE NOT NULL,
	PRIMARY KEY (MaThe),
	CONSTRAINT FK_The_SV FOREIGN KEY(MaSinhVien) REFERENCES dbo.SinhVien(MaSinhVien)
);
CREATE TABLE tPhieuMuon
(
	SoPhieuMuon NVARCHAR(10) NOT NULL,
	Masach NVARCHAR(10) NOT NULL,
	SoLuong TINYINT,
	PRIMARY KEY(SoPhieuMuon),
	CONSTRAINT FK_DS_Sach FOREIGN KEY(Masach) REFERENCES dbo.Sach(MaSach)
);
CREATE TABLE tChiTietPhieuMuon
(
	SoPhieuMuon NVARCHAR(10) NOT NULL,
	MaThe NVARCHAR(10) NOT NULL,
	MaNhanVien NVARCHAR(10) NOT NULL,
	NgayMuon DATE NOT NULL,
	NgayPhaiTra DATE NOT NULL,
	TrangThai NVARCHAR(10),
	PRIMARY KEY(SoPhieuMuon),
	CONSTRAINT FK_PM_The FOREIGN KEY(MaThe) REFERENCES dbo.TheMuon(MaThe),
	CONSTRAINT FK_PM_NV FOREIGN KEY(MaNhanVien) REFERENCES dbo.NhanVien(MaNhanVien),
	CONSTRAINT FK FOREIGN KEY(SoPhieuMuon) REFERENCES dbo.DSMuon(SoPhieuMuon)
);
CREATE TABLE tViPham
(
	MaThe NVARCHAR(10),
	MaViPham NVARCHAR(10),
	TenViPham NVARCHAR(20),
	NoiDung NVARCHAR(200),
	CONSTRAINT FK_ViPham_The FOREIGN KEY(MaThe) REFERENCES dbo.TheMuon(MaThe)
);

CREATE TABLE tTraSach
(
	SoPhieuMuon NVARCHAR(10) NOT NULL,
	MaSach NVARCHAR(10) NOT NULL,
	MaNV NVARCHAR(10),
	NgayTra DATE NOT NULL, 
	CONSTRAINT FK_Tra_Nv FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNhanVien),
	CONSTRAINT FK_Muon_Tra FOREIGN KEY(SoPhieuMuon) REFERENCES dbo.ChiTietPhieuMuon(SoPhieuMuon),
	CONSTRAINT FK_Tra_Sach FOREIGN KEY(MaSach) REFERENCES dbo.Sach(MaSach)
);

CREATE TABLE tTaiKhoan
(
	TaiKhoan VARCHAR(20) NOT NULL,
	MatKhau VARCHAR(20) NOT NULL,
	Role BIT NOT NULL

)